version: '3.8'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "5678:5678"
    volumes:
      - .:/app
    environment:
      FLASK_DEBUG: 1
    stdin_open: true
    tty: true
